name: ${project.name}
main: com.poixson.backroomslite.BackroomsLitePlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
depends:
  - pxnPluginLib
  - Multiverse-Core
authors: lorenzop
website: ${project.url}
description: ${project.description}
